### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm-GUI#2]
- [ ] add SIP registration
- [ ] fix all crashes
- [ ] add tool-tips for settings
- [ ] prettify output for participants in running session
- [ ] filter log by priority (only show anything above a given priority), defaults to INFO
- [ ] add CI with Travis and Appveyor, if they support Qt5
